language: node_js
sudo: required
node_js: stable

cache:
  directories:
    - node_modules 

before_script:
  - git clone --branch master https://github.com/gam2046/gam2046.github.io.git public
  
install:
  - npm install 
  - npm install -g hexo-cli
script:
  - hexo generate
after_script: 
  - cd ./public
  - git init
  - git config user.name "forDream"
  - git config user.email "gam2046@gmail.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master # 
  
branches:
  only:
    - hexo
env: 
 global:
   - GH_REF: github.com/gam2046/gam2046.github.io.git
